#Log Storage
deploymentMode: SingleBinary

loki:
  auth_enabled: false

  useTestSchema: true

  commonConfig:
    replication_factor: 1

  storage:
    type: filesystem

singleBinary:
  replicas: 1

  persistence:
    enabled: true
    size: 10Gi

backend:
  replicas: 0

read:
  replicas: 0

write:
  replicas: 0

gateway:
  enabled: false

monitoring:
  selfMonitoring:
    enabled: false

chunksCache:
  enabled: false

resultsCache:
  enabled: false