apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace/namespace.yaml
  - postgres/secret.yaml
  - postgres/pvc.yaml
  - ls -R manifests/postgres
  - postgres/service.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml