apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: saas-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/rohit-1947/saas-gitops.git
    targetRevision: main
    path: manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: saas-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true