config:
  clients:
    - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push

daemonset:
  enabled: true

deployment:
  enabled: false

serviceMonitor:
  enabled: false

rbac:
  create: true

serviceAccount:
  create: true